#!/bin/bash
# задаём переменную
isactive=$(sudo wg show | grep -c wg0)
if sudo wg show | grep -c wg0 2>&1 >/dev/null
then
# /dev/null 2>&1 - отключает вывод у указанного уровня вывода в терминал
wg-quick down wg0 > /dev/null 2>&1 && echo "VPN Deactivate"
# если переменная equal (равна)
elif [ $isactive -eq 0 ]
then
wg-quick up wg0 > /dev/null 2>&1 && echo "VPN Activate"
fi
